version: '{build}'

environment:
  matrix:
    - PYTHON: "C:\\Python38-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python36-x64"

install:
  - ps: Install-Product Python $env:PYTHON
  - set PATH=C:\Python%PYTHON:~0,1%%PYTHON:~-3%;%PATH%
  - pip install -r requirements.txt

build_script:
  - python setup.py build

test_script:
  - python setup.py test
