version: 2.1

orbs:
  python: circleci/python@1.0

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Build package
          command: |
            python setup.py sdist bdist_wheel

workflows:
  build:
    jobs:
      - build
